### ISSUE TITLE
NPM versión 1.0.0

### ISSUE THREAD

**Issue by javigaralva** [aespinilla/faparser#1]
Hola. 
En NPM está la versión 1.0.0, que tiene el bug de los directores. 

Un saludo y muchas gracias por este gran paquete.

**Comment by aespinilla** [comment]
Hola!

Ya he actualizado en NPM la versión del proyecto. Ya puedes hacer un npm update y te descargará la nueva versión con el bug de los directores reparado.

Muchas gracias por usarla y avisarme, que se me había olvidado subirlo. Un saludo.
