### ISSUE TITLE
Issue with cheerio

### ISSUE THREAD

**Issue by jobarjo** [aespinilla/faparser#4]
Hello,

I've been using your package for some time now but it recently (not sure exactly when in the last X months) stopped working.

Seems to be something due with [this line](https://github.com/aespinilla/faparser/blob/master/parser.js#L233) when submitting the following request:

```
{
    query: "the matrix",
    lang: 'uk',
    type: fa.TITLE,
    start: 0,
  }
```

the error received is:

```
TypeError: Cannot read property 'filter' of undefined
    at .../src/node_modules/faparser/node_modules/cheerio/lib/api/traversing.js:30:42
    at Array.reduce (<anonymous>)
    at module.exports.exports.find (.../src/node_modules/faparser/node_modules/cheerio/lib/api/traversing.js:29:30)
    at Object.parseSearch (.../src/node_modules/faparser/parser.js:233:17)
    at .../src/node_modules/faparser/faparser.js:24:35
    ....
```

It was working on your version `1.0.6` which uses cheerio `1.0.0-rc.3` but stopped with `1.0.8` that is using cheerio `1.0.0-rc.5`.

I've never used cheerio that it's hard for me to go deeper and find what's wrong.
Appreciate the feedack!

Cheers
Joel

**Comment by aespinilla** [comment]
Hello! I will check this bug. 

Thank you very much for your bug report.

**Comment by aespinilla** [comment]
I have just release 1.0.9 available on npm. Just force cheerio version to rc2.

Thank you again. ;)
