### ISSUE TITLE
Redirect not supported

### ISSUE THREAD

**Issue by jobarjo** [aespinilla/faparser#7]
Hello again :-)

I see you changed the deprecated `request` package for `bent`. This had the unfortunate effect of not supporting redirects anymore.

A search like this: `https://www.filmaffinity.com/uk/search.php?stype=title&stext=alien%20tv&from=0&orderby=year` that used to be supported and parsed by your package now fails with the following:
```
{
  code: 303,
  url: 'https://www.filmaffinity.com/uk/search.php?stype=title&stext=alien%20tv&from=0&orderby=year',
  error: 'See Other'
}
```

Unfortunately, I couldn't see options for bent to support redirects. 

There are other good packages out there though and I'm myself using quite a lot [superagent](https://www.npmjs.com/package/superagent) that [supports redirects](https://visionmedia.github.io/superagent/#following-redirects).

Would it possible to make that change?

Cheers
Joel

**Comment by jobarjo** [comment]
Also, I think that the other changes to the code makes this request not return anything, when it was returning the right results with the previous version. I tried to investigate the code change but not fully understanding the ins and outs, it's not simple for me :-)

**Comment by aespinilla** [comment]
Hi!

Sorry for the bug. I have restored the 'request' library. It's handle redirections. Soon I will update this library with new suggested requests libraries.

You can upgrade your library to 1.1.1 with this fix. I'm not going to close this issues until you confirm this fix is sucessful jaja.

Thank you very much.

**Comment by jobarjo** [comment]
Thanks, it works all good now :-)
